### ISSUE TITLE
cannot open LUA_PATHconfig.lua

### ISSUE THREAD

**Issue by S3riousSam** [bfeldpw/battlesub#1]
After building the project succesfullly, I launch the game (using the "run" script) and get this error:

`
[sol2] An error occurred and has been passed to an error handler: sol: file error: cannot open LUA_PATHconfig.lua: No such file or directory
terminate called after throwing an instance of 'sol::error'
  what():  sol: file error: cannot open LUA_PATHconfig.lua: No such file or directory
./scripts/run: line 9: 17003 Aborted                 (core dumped) ./install/bin/battle_sub
`

Anyy hint to help fix this issue?

**Comment by bfeldpw** [comment]
Hm, I'll try to figure it out, unfortunately, I can't reproduce and the last time, the CI ran successfully as well. Do you see any differences in the .travis.yml compared to your local system?
While sol should be fine with different lua versions, there might be a conflict, since lua5.{1,2,3} might have breaking changes or especially luajit got some differences, if I remember correctly.

**Comment by S3riousSam** [comment]
I finally got it working (Kubuntu 18.04) (I had to specify the proper path for LD_LIBRARY_PATH and installed some packages (maybe package lua5.3 did the trick?).
